REPLACE INTO xcart_languages SET code='en', name='eml_acr_new_review_subj', value='New review has been added by customer', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_acr_review_reminder_subj', value='Dear {{user}}, your opinion matters to {{company_name}}', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_add_review', value='Add your own review', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_add_review_error', value='Some errors occurred  when trying to save review.<br />\r\nThe review has not been added', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_advantages', value='Advantages', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_allow_to_all', value='All customers', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_allow_to_buyers', value='Customers who bought product', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_allow_to_registered', value='Registered customers', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_approved', value='Approved', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_author', value='Author', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_author_info', value='Author information', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_average_customer_rating', value='Average customer rating', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_back_to_reviews_list', value='Back to reviews list', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_click_dropdown', value='Click to view detailed information', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_comment', value='Comment', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_count_reviews', value='{{count}} review(s)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_customer_purchased_item', value='This customer purchased the item at our site.', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_customer_reviews', value='customer reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_disadvantages', value='Disadvantages', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_edit_review', value='Edit review', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_email_optional', value='optional', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_guest', value='Guest', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_is_review_useful', value='Was the above review useful to you?', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_max_length', value='Maximum length is {{length}} characters', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_menu_reviews', value='Reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_most_useful', value='Most useful first', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_most_useful_reviews', value='Most useful customer reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_m_out_of_n', value='{{m}} out of {{n}}', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_need_login', value='Only registered customers are allowed to add review. Please <a href=\"{{href}}\"{{additional}}>sign in</a> and add your own review!', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_need_purchase', value='Only those who bought this product are allowed to add review', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_need_purchase_login', value='If you\'ve already bought this product, please <a href=\"{{href}}\"{{additional}}>sign in</a> and add your own review!', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_newest', value='Newest first', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_newest_reviews', value='Most recent customer reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_no_date', value='(no date)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_n_stars', value='{{count}} stars', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_pending', value='Pending', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_products_reviews_meta_descr', value='Products reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_products_reviews_meta_title', value='Products reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_product_reviews_meta_descr', value='Product reviews for ', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_product_reviews_meta_title', value='Product reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_random_reviews', value='Random reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_rating', value='Rating', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_rating_based', value='(based on {{votes_count}} votes and {{reviews_count}} reviews)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_rating_based_on_n_reviews', value='(based on {{reviews_count}} reviews)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_rating_based_on_n_votes_n_reviews', value='(based on {{votes_count}} votes and {{reviews_count}} reviews)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_read_all_reviews', value='Read all reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_read_product_reviews', value='Read more product reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_read_reviews', value='Read more reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_rejected', value='Rejected', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_reviews', value='reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_reviews_management', value='Customer Reviews Management', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_about', value='about', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_comments', value='Review comments', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_for', value='write a review for', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_info', value='Review information', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_is_added', value='Review has been added', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_is_added_customer', value='Thank you for posting your review! It has been successfully added.', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_is_added_pending', value='Your review will appear in the list after admin approval.', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_is_updated', value='Review has been updated', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_is_verified', value='Review is verified<br />(customer purchased product at this site)', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_review_status', value='Status', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_reviews_title', value='Product reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_search_reviews', value='Search reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_see_all_n_reviews', value='See all {{count}} reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_see_all_reviews', value='see all reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_sort_by_review_rating', value='Rating', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_star', value='star', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_status', value='Status', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_update_products_review_rating', value='Recalculating average products rating based on reviews...', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_update_review_error', value='Some errors occurred when trying to save review.<br />\r\nThe review has not been updated', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_viewing_n_stars_reviews', value='You are viewing <b>{{count}}-stars</b> reviews', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_your_comment', value='Your comment', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_your_email', value='Your email', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_your_rating', value='Your rating', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_acr_you_already_reviewed', value='You have already written a review for this product', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='module_descr_Advanced_Customer_Reviews', value='This module enables advanced customer reviews management (ratings, moderation)<br /><b>Note:</b> This module requires Customer Reviews module to be disabled.', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='module_name_Advanced_Customer_Reviews', value='Advanced Customer Reviews', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='msg_acr_err_email', value='You have specified an incorrect email address.', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='msg_acr_err_rating', value='Please rate product (0-stars is not allowed).', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='option_title_Advanced_Customer_Reviews', value='Advanced Customer Reviews', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_admin_reviews_per_page', value='Reviews per page (admin area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_allow_change_useful_box_vote', value='Allow customers change their vote in the \"Was the above review useful to you?\" box', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_allow_sort_by_rating', value='Allow sort products by rating (customer area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_customer_reviews_order', value='Default reviews order (customer area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_customer_reviews_per_page', value='Reviews per page (customer area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_customer_reviews_per_product', value='Reviews per product details page (customer area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_default_status', value='Default status for new review', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_display_reviews_menu', value='Display customer reviews menu (customer area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_display_useful_box', value='Display \"Was the above review useful to you?\" box', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_email_addresses_new_review', value='Notification email addresses (use \',\' to separate multiple email addresses)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_first_orderid_for_reminder', value='Start send review reminder for orders with orderid greater than or equal to', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_max_stars', value='Stars in product rating scale', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_min_rating_for_reviews_menu', value='Display reviews with N-stars and higher rating only', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_reviews_menu_order', value='Reviews order in customer menu', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_review_reminder_key', value='Secure key for launching review reminder script (send_review_reminders.php)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_send_email_about_new_review', value='Receive an email notification when new review is posted', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_send_reminder_in_n_days', value='Send review reminder to customer in N days', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_send_review_reminder', value='Send review reminder to customer (for completed orders)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_use_advantages_block', value='Show \"Advantages\" and \"Disadvantages\" blocks?', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_use_old_ratings', value='Use old ratings values for general product rating', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_acr_writing_reviews', value='Who must be allowed to add reviews', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_descr_acr_review_reminder_key', value='If key is set as a2gHudkv81bpqrm61ft then command for launching the script is:<br /><br />\r\nphp &lt;path_to_xcart&gt;/send_review_reminders.php --key=a2gHudkv81bpqrm61ft <br /><br />\r\nOR <br /><br />\r\nhttp://example.com/send_review_reminders.php?key=a2gHudkv81bpqrm61ft<br />', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_acr1', value='General Customer Reviews options', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_acr2', value='Appearance options', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_acr3', value='Customer Reviews Menu Box options', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_acr4', value='Email notifications options', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_acr5', value='Review Reminder options', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_add_products_reviews', value='Thank you for your recent purchase from {{company_name}}.<br />\r\nWe  hope you\'ll take a couple of minutes to write a review to the purchased products and share your experience with other customers. We would appreciate it very much.\r\n<br /><br />\r\nWrite a review is quite simple: click on the link with the product name.', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_add_review', value='Share your experience with other customers. Submit your tips or thought on this product, be detailed and specific.', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_add_review_about_product', value='Share your experience about <a href=\"product.php?productid={{productid}}\">{{product}}</a> with other customers. Submit your tips or thought on this product, be detailed and specific.', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_delete_reviews_warning', value='Are you sure that you want to delete selected reviews?', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_email_optional_descr', value='Your email will not be visible to other customers', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_new_review', value='New review has been added', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_no_customer_reviews', value='There have been no reviews', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_no_date', value='(original date is undefined since this review was added before altering \'datetime\' column for the reviews)', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_search_edit_reviews', value='This section allows you to search and edit customer reviews.', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_search_substr', value='Search in \"Comment\", \"Advantages\", \"Disadvantages\" text', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_acr_verified_review', value='Your review will be marked as \"Verified\" since you\'ve purchased this product at our site (orders {{orders}})', topic='Text';
