INSERT INTO xcart_languages SET code='en', name='lbl_banner_system', value='Banner System', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_add_content', value='Add content', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_add_banner_content', value='Add banner content', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_add_html_code', value='Add HTML code', topic='Text';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_add_image', value='Add image', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_back_to_banners_list', value='Back to banners list', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_back_to_locations_list', value='Back to locations list', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_content', value='Banner content', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_effect', value='Banner effect', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_end_date', value='End date', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_images', value='Banner images', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_height', value='Banner height', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_html_code', value='Banner HTML content', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_location', value='Banner location', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_navigation', value='Navigation', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_start_date', value='Start date', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_width', value='Banner width', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_banner_unlimited', value='Unlimited', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_bottom_banners', value='Bottom banners', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_choose_banner_location', value='Please choose banner location:', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_edit_banner_content', value='Edit banner content', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_home_page', value='Home page', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_left_column', value='Left column', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_left_column_banners', value='Left column banners', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_right_column', value='Right column', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_right_column_banners', value='Right column banners', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_secondary_pages', value='Secondary pages', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='lbl_bs_top_banners', value='Top banners', topic='Labels';

INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_banners_del', value='The selected banners have been deleted.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_banners_upd', value='The banners have been updated.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_image_added', value='Image has been added.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_images_removed', value='Images have been removed.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_html_added', value='HTML code has been added.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_html_removed', value='HTML code has been removed.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_bs_adm_wrong_type', value='Wrong data type!', topic='Text';

INSERT INTO xcart_languages SET code='en', name='txt_bs_banner_colors_note', value='<strong>NOTE:</strong><br/>Banners marked in <span style=\"color: #0000ff;\">blue</span> color have a start date set in the future.<br />Banners marked in <span style=\"color: #ff0000;\">red</span> are expired.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='txt_bs_banner_content_top_text', value='The banner can be filled with images or HTML code. Please choose "Add image" or "Add HTML code" tab.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='txt_bs_no_banners_defined', value='No banners defined.', topic='Text';

INSERT INTO xcart_languages SET code='en', name='lbl_image_title_A', value='Banner System images', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='module_descr_Banner_System', value='This module provides a banner management system for your store.', topic='Modules';
INSERT INTO xcart_languages SET code='en', name='module_name_Banner_System', value='Banner System', topic='Modules';
INSERT INTO xcart_languages SET code='en', name='opt_bs_rotation_time_delay', value='Banner rotation time delay (seconds)', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_descr_bs_rotation_time_delay', value='The length of time a banner image or HTML content is displayed within the banner container before being replaced with the next image/HTML content piece.', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_descr_default_banner_height', value='The height to be used for all banners that do not have a non-zero height value defined in their properties.', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_default_banner_height', value='Default banner height', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_descr_default_banner_width', value='The width to be used for all banners that do not have a non-zero width value defined in their properties.', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_default_banner_width', value='Default banner width', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_unlimited_banners_time', value='Unlimited banner display time', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_descr_unlimited_banners_time', value='This option sets unlimited display time for all banners. If it is enabled, banner display time settings of individual banners are ignored.', topic='Options';
