INSERT INTO xcart_languages SET code='en', name='lbl_mailchimp_news_management', value='MailChimp management', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='msg_adm_mailchimp_connection_configured', value='Connection to MailChimp is configured.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='msg_adm_mailchimp_newslists_imported', value='MailChimp newslists are imported.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='msg_adm_mailchimp_newslists_import_error', value='Can\'t import MailChimp lists. Check MailChimp settings.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='msg_adm_mailchimp_newslists_no_lists', value='There are not any lists configured. Please login to MailChimp to create lists.', topic='Labels';
INSERT INTO xcart_languages SET code='en', name='txt_mailchimp_news_management_top_text', value='This section allows you to manage your MailChimp news lists: import news lists and rename newslists. Please read MailChimp module manual at <a href=\"http://help.qtmsoft.com/index.php?title=X-Cart:X-MailChimp_Integration_module\">http://help.qtmsoft.com</a>', topic='Text';
INSERT INTO xcart_languages SET code='en', name='module_descr_Adv_Mailchimp_Subscription', value='This module allows to use MailChimp newsletters management service. To create a MailChimp account please <a href="http://www.mailchimp.com/signup/?pid=xcart&amp;source=website" target="_blank">click here</a>.', topic='Modules';
INSERT INTO xcart_languages SET code='en', name='module_name_Adv_Mailchimp_Subscription', value='MailChimp', topic='Modules';
INSERT INTO xcart_languages SET code='en', name='opt_adv_mailchimp_analytics', value='Enable Analytics 360 for Mailchimp', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_adv_mailchimp_apikey', value='API Key : You can grab your API Key from here: http://admin.mailchimp.com/account/api-key-popup', topic='Options';
INSERT INTO xcart_languages SET code='en', name='opt_adv_mailchimp_register_opt', value='Enable confirmation request for subscription from users profile page', topic='Options';
