REPLACE INTO `xcart_languages` SET `code`='en', `name`='module_name_XMultiCurrency', `value`='MultiCurrency', `topic`='Modules';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='module_descr_XMultiCurrency', `value`='This module adds multicurrency feature for your store.', `topic`='Modules';

REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_service_gfin', `value`='Google Finance Currency Converter', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_service_gconv', `value`='Google Currency Convertion API', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_service_webservicex', `value`='WebserviceX.NET', `topic`='Labels';

REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_multicurrency_menu', `value`='Currencies', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_currencies_management', `value`='Currency management', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_currencies_updated', `value`='Currencies updated successfully', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_currency_added', `value`='Currency added successfully', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_currency_already_added', `value`='Currency already exists', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_currency_rates_updated', `value`='Currency rates updated successfully', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_primary_currency_delete_warning', `value`='Primary currency cannot be deleted', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_primary_currency_switch_warning', `value`='Primary currency state cannot be changed', `topic`='Labels';

REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_primary', `value`='Primary', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_currency', `value`='Currency', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_code', `value`='Code', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_symbol', `value`='Symbol', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_format', `value`='Format', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_number_format', `value`='Number format', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_rate', `value`='Rate', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_updated', `value`='Updated', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_rates_last_updated', `value`='Rates last updated:', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_offline', `value`='offline', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_method', `value`='method:', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_seconds', `value`='sec', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_add_currency', `value`='Add currency', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_add', `value`='Add currency', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_update_rates', `value`='Update rates', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_online_service', `value`='Online service', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_update_rates_now', `value`='Update rates right now', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_enable_autoupdate', `value`='Automatically update currency exchange rates daily', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_time_of_update', `value`='Time of update (HH:MM)', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_update_options', `value`='Update selector options', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_selector_note_admin', `value`='Note: MultiCurrency module adds a popup selector which allows customers to choose language (if several languages defined), currency (if more than one currency specified) and country. First time visitors\' country is detected automatically by their IP address. Language and currency are preselected according to the detected country and remembered in cookies. You can disable changing country on the popup selector.', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_allow_select_country', `value`='Allow customers to select country', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_selector_title', `value`='Select...', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_select_surrency', `value`='Select currency', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_select_coountry', `value`='Select your country', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_currency_note', `value`='Note: All prices billed in {{currency}} ({{symbol}}). Currency conversion is approximate. Current exchange rate is {{X}} = {{Y}}', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lblcurrency_note2', `value`='Note: All prices billed in {{currency}}. Currency conversion is approximate. Current exchange rate is {{X}} = {{Y}}', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_txt_currency_note_order', `value`='Note: Order has been billed in {{currency}} ({{symbol}}). Currency conversion is approximate. Exchange rate for the order placement date ({{X}} = {{Y}}).', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_amount_billed', `value`='Amount you were billed for ({{X}})', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_time_of_update_note', `value`='Specify hours as a two digits (00 through 23), without am/pm. This time is the web server time (e.g. current web server time is {{T}})', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_use_custom_countries', `value`='List only countries with currencies set on the currency list', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_use_custom_countries_note', `value`='Enabling this option limits the country list by countries with currencies defined on the above currency list. Clearing this check box lists all countries.', `topic`='Labels';

REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_enabled', `value`='Enabled. Click to disable', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_disabled', `value`='Disabled. Click to enable', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_pos', `value`='Pos.', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_default_currency', `value`='Default storefront currency', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_select_default_currency', `value`='Choose default storefront currency', `topic`='Labels';
REPLACE INTO `xcart_languages` SET `code`='en', `name`='mc_lbl_default_currency_note', `value`='The selected currency will be used as a default in storefront if it was impossible to detect default currency by first time visitor\'s country.', `topic`='Labels';
