REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_B', value='<p>This notification is to inform you that the product <a href=\"{{product_url}}\" target=\"_blank\"><b>&quot;{{product}} ({{sku}})&quot;</b></a> is back in stock.</p>\r\n<p>Product page: <a href=\"{{product_url}}\" target=\"_blank\">{{product_url}}</a></p>\r\n', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_L', value='<p>This notification is to inform you that amount of the product <a href=\"{{product_url}}\" target=\"_blank\"><b>&quot;{{product}} ({{sku}})&quot;</b></a> has been decreased. There are {{amount}} items of this product in stock now.\r\n</p>\r\n<p>Product page: <a href=\"{{product_url}}\" target=\"_blank\">{{product_url}}</a></p>', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_P', value='<p>This notification is to inform you that price of the product <a href=\"{{product_url}}\" target=\"_blank\"><b>&quot;{{product}} ({{sku}})&quot;</b></a> has been dropped.</p>\r\n<p>Product page: <a href=\"{{product_url}}\" target=\"_blank\">{{product_url}}</a></p>', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_subj_B', value='Product is back in stock', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_subj_L', value='Low product quantity notification', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_subj_P', value='Product price drop notification', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='eml_prod_notif_unsubscribe', value='<p>If you do not want to receive such notifications of this product, please use the following link to unsubscribe:</p>\r\n<p><strong><a href=\"{{url}}\" target=\"_blank\">{{url}}</a></strong></p>\r\n', topic='E-Mail';
REPLACE INTO xcart_languages SET code='en', name='err_prod_notif_email', value='Invalid email address!', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='err_submit_prod_notif_unknown', value='Error', topic='Errors';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm', value='Product notifications', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_date', value='Date', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_delete', value='Unsubscribe selected', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_email', value='Email', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_product', value='Product', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_product_name', value='<a href=\"{{link}}\" target=\"_blank\"><b>#{{productid}}</b> {{product}} (SKU: {{productcode}})</a>', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_requestor', value='Requestor', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_search', value='Filter notifications', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_search_button', value='Filter', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_search_results', value='Notifications list', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_type', value='Type', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_type_name_B', value='Back-in-stock', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_type_name_L', value='Low-stock', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_adm_type_name_P', value='Price-drop', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_anon_requestor', value='anonymous', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_button_tip_B', value='Click here to subscribe for \'Back-in-stock\' notifications', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_button_tip_L', value='Click here to be notified when this item is nearly out of stock', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_button_tip_P', value='Click here to be notified of price drops of this item', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_email_default', value='e-mail', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_submit', value='Submit', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='lbl_prod_notif_waiting_msg', value='Waiting', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='module_name_Product_Notifications', value='Product Notifications', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='module_descr_Product_Notifications', value='This module allows customer to receive inventory-related and price-related notifications', topic='Modules';
REPLACE INTO xcart_languages SET code='en', name='msg_adm_prod_notif_del', value='Selected notifications has been deleted', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='msg_prod_notif_unsubscribed_cust', value='You have been unsubscribed successfully.', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='msg_profile_add_activation_email', value='Profile has been successfully created. The account activation link has been sent to the provided email.', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='msg_submit_prod_notif_ok', value='You have been subscribed', topic='Labels';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_adm_obj_per_page', value='Product notifications per page (in the admin area)', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_enabled_B', value='Enable \'Back in stock\' notifications', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_enabled_L', value='Enable \'Low stock\' notifications', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_enabled_P', value='Enable \'Price drop\' notifications', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_L_amount', value='Minimal product available amount for low-stock notifications', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_show_in_list_B', value='Show notification request forms in the product list', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_show_in_list_L', value='Show notification request forms in the product list', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_prod_notif_show_in_list_P', value='Show notification request forms in the product list', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_prod_notif_B', value='\'Back in stock\' notifications settings', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_prod_notif_general', value='General product notifications settings', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_prod_notif_L', value='\'Low stock\' notifications settings', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='opt_sep_prod_notif_P', value='\'Price drop\' notifications settings', topic='Options';
REPLACE INTO xcart_languages SET code='en', name='txt_prod_notif_adm_no_results', value='No records', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_prod_notif_adm_top_text', value='This section allows you to manage product notifications', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_prod_notif_request_B', value='Notify me when this item is back in stock', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_prod_notif_request_L', value='Notify me when this item is nearly out of stock', topic='Text';
REPLACE INTO xcart_languages SET code='en', name='txt_prod_notif_request_P', value='Notification will be sent to your e-mail address every time the item price is decreased.', topic='Text';
INSERT INTO xcart_languages SET code='en', name='msg_prod_notif_already_subscribed', value='You already subscribed', topic='Labels';
